pip install cryptacular
pip install BeautifulSoup
pip install sqlalchemy==0.7.10
pip install flask
pip install flask-login
pip install flask-sqlalchemy
pip install sqlalchemy-migrate
pip install flask-whooshalchemy
pip install flask-wtf
pip install WebHelpers2
pip install flup
pip install pep8
