pip install cryptacular
pip install sqlalchemy==0.7.10
pip install flask-principal
pip install flask
pip install flask-login
pip install flask-sqlalchemy
pip install sqlalchemy-migrate
pip install flask-whooshalchemy
pip install flask-wtf
pip install flup
